r=int(input("Nhap vao ban kinh cua duong tron: "))
S=float(3.14*(r**2))
C=float(2*r*3.14)
print("Dien tich cua duong tron co ban kinh",r,"la =",round(S,1))
print("Chu vi cua duong tron co ban kinh",r,"la =",round(C,1))